=== culturecommunication/octave/docuteam-packer-dist/src/main/resources/config/csv-mapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="ch:docuteam:mapping:csv" targetNamespace="ch:docuteam:mapping:csv"
    elementFormDefault="qualified">
    <xs:element name="importTableConfig">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="csvFormat"/>
                <xs:element name="checkAllLines" type="xs:boolean" default="false" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>Check that all lines of the CSV file are referencing an existing node of the SIP.</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="checkAllNodes" type="xs:boolean" default="false" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>Check that all nodes of the SIP are referenced in the CSV file.</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="existingValues" type="existingValueType" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>Indicate how to handle existing values:
- skip: ignore the value from the CSV file.
- overwrite: replace existing values with values (if existing) from the CSV file.
- add: keep the existing value and add the value from the CSV file as an additional field.</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:choice>
                    <xs:element name="referenceColumnNumber" type="xs:integer">
                        <xs:annotation>
                            <xs:documentation>Indicate the number of the column containing the references (relative paths) to the nodes within the SIP.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="referenceColumnLabel" type="xs:NMTOKEN">
                        <xs:annotation>
                            <xs:documentation>Indicate the label of the column containing the references (relative paths) to the nodes within the SIP.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:choice>
                <xs:element ref="columnMapping" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="csvFormat">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="charset" type="xs:string" default="UTF-8" minOccurs="0"/>
                <xs:element name="delimiter" type="delimiter" default=";" minOccurs="0"/>
                <xs:element name="escapeCharacter" type="escapeCharacter" minOccurs="0"/>
                <xs:element name="quoteCharacter" type="quoteCharacter" default="&quot;" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>

    </xs:element>

    <xs:simpleType name="delimiter">
        <xs:restriction base="xs:string">
            <xs:length fixed="true" value="1"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="escapeCharacter">
        <xs:restriction base="xs:string">
            <xs:length fixed="true" value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="quoteCharacter">
        <xs:restriction base="xs:string">
            <xs:length fixed="true" value="1"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="existingValueType">
        <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="skip"/>
            <xs:enumeration value="overwrite"/>
            <xs:enumeration value="add"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="columnMapping">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="column" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="column">
        <xs:annotation>
            <xs:documentation>Specify a mapping indicating the header of a column from the CSV file and an accessorID from the Matterhorn METS standard (referring an EAD element).</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:attribute name="tableHeaderLabel" use="required" type="xs:string"/>
            <xs:attribute name="matterhornMetsAccessorID" use="required" type="matterhornFieldType"/>
        </xs:complexType>
    </xs:element>


    <!--
    ################################
    ### Field types : matterhorn ###
    ################################
    -->

    <xs:simpleType name="matterhornFieldType">
        <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="abstract"/>
            <xs:enumeration value="accessionNumber"/>
            <xs:enumeration value="accessNr"/>
            <xs:enumeration value="accessPolicy"/>
            <xs:enumeration value="accessRestriction"/>
            <xs:enumeration value="accessRestrictionClassification"/>
            <xs:enumeration value="accessRestrictionClosureYear"/>
            <xs:enumeration value="accessRestrictionExplanation"/>
            <xs:enumeration value="accessRestrictionIsMetadataPublic"/>
            <xs:enumeration value="accessRestrictionIsPublic"/>
            <xs:enumeration value="accessRestrictionPeriod"/>
            <xs:enumeration value="accessRestrictionPeriodBaseYear"/>
            <xs:enumeration value="accessRestrictionPrivacy"/>
            <xs:enumeration value="accessRestrictionStatus"/>
            <xs:enumeration value="accessRestrictionStatusExplanation"/>
            <xs:enumeration value="accruals"/>
            <xs:enumeration value="appraisalAndDestruction"/>
            <xs:enumeration value="appraisalDateDisposed"/>
            <xs:enumeration value="appraisalIsOnHold"/>
            <xs:enumeration value="appraisalRetentionPeriod"/>
            <xs:enumeration value="archivalHistory"/>
            <xs:enumeration value="arrangement"/>
            <xs:enumeration value="author"/>
            <xs:enumeration value="authorGeneric"/>
            <xs:enumeration value="bibliography"/>
            <xs:enumeration value="biographicalHistory"/>
            <xs:enumeration value="cartographicMaterial"/>
            <xs:enumeration value="characteristics"/>
            <xs:enumeration value="characteristicsNote"/>
            <xs:enumeration value="codeLocation"/>
            <xs:enumeration value="comment"/>
            <xs:enumeration value="compartment"/>
            <xs:enumeration value="conditionsOfReproductions"/>
            <xs:enumeration value="creationPeriod"/>
            <xs:enumeration value="creationPeriodNotes"/>
            <xs:enumeration value="creator"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="dateOfBirth"/>
            <xs:enumeration value="deathOfAuthor"/>
            <xs:enumeration value="descriptionLevel"/>
            <xs:enumeration value="descriptionLevelNotes"/>
            <xs:enumeration value="descriptionRules"/>
            <xs:enumeration value="designer"/>
            <xs:enumeration value="digitization"/>
            <xs:enumeration value="dimensions"/>
            <xs:enumeration value="dimensionsCategory"/>
            <xs:enumeration value="DOI"/>
            <xs:enumeration value="DoiJournal"/>
            <xs:enumeration value="edition"/>
            <xs:enumeration value="editionStatement"/>
            <xs:enumeration value="editor"/>
            <xs:enumeration value="event"/>
            <xs:enumeration value="extent"/>
            <xs:enumeration value="extentNote"/>
            <xs:enumeration value="extentPrint"/>
            <xs:enumeration value="extentUnit"/>
            <xs:enumeration value="familyName"/>
            <xs:enumeration value="filePlanPosition"/>
            <xs:enumeration value="fileUrl"/>
            <xs:enumeration value="fileName"/>
            <xs:enumeration value="fileMimeType"/>
            <xs:enumeration value="findingAids"/>
            <xs:enumeration value="firstname"/>
            <xs:enumeration value="format"/>
            <xs:enumeration value="from"/>
            <xs:enumeration value="fromYear"/>
            <xs:enumeration value="fullLocation"/>
            <xs:enumeration value="function"/>
            <xs:enumeration value="fundingSource"/>
            <xs:enumeration value="geogName"/>
            <xs:enumeration value="illustrator"/>
            <xs:enumeration value="institute"/>
            <xs:enumeration value="institution"/>
            <xs:enumeration value="institutionCreator"/>
            <xs:enumeration value="institutionInvolved"/>
            <xs:enumeration value="invalid"/>
            <xs:enumeration value="involved"/>
            <xs:enumeration value="ISBN"/>
            <xs:enumeration value="ISSN"/>
            <xs:enumeration value="journal"/>
            <xs:enumeration value="keyword"/>
            <xs:enumeration value="language"/>
            <xs:enumeration value="languageNotes"/>
            <xs:enumeration value="lastname"/>
            <xs:enumeration value="letter"/>
            <xs:enumeration value="levelOfDescription"/>
            <xs:enumeration value="location"/>
            <xs:enumeration value="locationOfOriginals"/>
            <xs:enumeration value="material"/>
            <xs:enumeration value="method"/>
            <xs:enumeration value="modeOfAcquisition"/>
            <xs:enumeration value="nationality"/>
            <xs:enumeration value="objectType"/>
            <xs:enumeration value="occupation"/>
            <xs:enumeration value="origination"/>
            <xs:enumeration value="originationAgency"/>
            <xs:enumeration value="originationDepartment"/>
            <xs:enumeration value="otherLevelName"/>
            <xs:enumeration value="photographer"/>
            <xs:enumeration value="PID"/>
            <xs:enumeration value="placeOfPublication"/>
            <xs:enumeration value="premisEventDetail"/>
            <xs:enumeration value="premisEventDateTime"/>
            <xs:enumeration value="premisEventType"/>
            <xs:enumeration value="premisEventOutcomeDetail"/>
            <xs:enumeration value="processInfoArchivist"/>
            <xs:enumeration value="processInfoDate"/>
            <xs:enumeration value="project"/>
            <xs:enumeration value="projectAbbreviation"/>
            <xs:enumeration value="projectName"/>
            <xs:enumeration value="projectTitle"/>
            <xs:enumeration value="publication"/>
            <xs:enumeration value="publisher"/>
            <xs:enumeration value="refCode"/>
            <xs:enumeration value="refCodeAdmin"/>
            <xs:enumeration value="refCodeIsVisible"/>
            <xs:enumeration value="refCodeOld"/>
            <xs:enumeration value="refCodeSeparator"/>
            <xs:enumeration value="relatedMaterial"/>
            <xs:enumeration value="relatedMaterialExtern"/>
            <xs:enumeration value="relationPeriod"/>
            <xs:enumeration value="reproductions"/>
            <xs:enumeration value="responsible"/>
            <xs:enumeration value="retentionPeriod"/>
            <xs:enumeration value="retentionPeriodBaseYear"/>
            <xs:enumeration value="retentionPolicy"/>
            <xs:enumeration value="revisions"/>
            <xs:enumeration value="scale"/>
            <xs:enumeration value="scopeContent"/>
            <xs:enumeration value="sex"/>
            <xs:enumeration value="size"/>
            <xs:enumeration value="sourceType"/>
            <xs:enumeration value="special"/>
            <xs:enumeration value="staff"/>
            <xs:enumeration value="status"/>
            <xs:enumeration value="subject"/>
            <xs:enumeration value="subjectGeneral"/>
            <xs:enumeration value="submitStatus"/>
            <xs:enumeration value="to"/>
            <xs:enumeration value="toYear"/>
            <xs:enumeration value="typeOfAcquisition"/>
            <xs:enumeration value="uniformTitle"/>
            <xs:enumeration value="unitTitle"/>
            <xs:enumeration value="unitTitleAdditional"/>
            <xs:enumeration value="unitTitleOriginal"/>
            <xs:enumeration value="unitTitleVarying"/>
            <xs:enumeration value="university"/>
            <xs:enumeration value="usage"/>
            <xs:enumeration value="usagePermission"/>
            <xs:enumeration value="usagePermissionExpiringDate"/>
            <xs:enumeration value="year"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== culturecommunication/octave/docuteam-packer/src/test/resources/config/csv-mapping.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- the defaults below refer to a CSV produced by Archifiltre in the ReSIP format -->
<importTableConfig xmlns="ch:docuteam:mapping:csv"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="ch:docuteam:mapping:csv csv-mapping.xsd">

    <csvFormat>
        <charset>UTF-8</charset>
        <delimiter>;</delimiter>
        <quoteCharacter>&quot;</quoteCharacter>
    </csvFormat>

    <checkAllLines>true</checkAllLines>
    <checkAllNodes>false</checkAllNodes>
    <existingValues>overwrite</existingValues>
    <referenceColumnLabel>Path</referenceColumnLabel>

    <columnMapping>
        <column tableHeaderLabel="unitTitle" matterhornMetsAccessorID="unitTitle" />
    </columnMapping>

</importTableConfig>
