=== culturecommunication/octave/docuteam-packer/src/test/resources/config/levels.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	targetNamespace="http://www.docuteam.ch/xmlns/levels"
	elementFormDefault="qualified"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.docuteam.ch/xmlns/levels">

	<xsd:element name="Config" type="ConfigType"></xsd:element>

	<xsd:complexType name="ConfigType">
		<xsd:all>
			<xsd:element name="MetadataElements" type="MetadataElementsType" minOccurs="0" maxOccurs="1"></xsd:element>
			<xsd:element name="Levels" type="LevelsType" minOccurs="1" maxOccurs="1"></xsd:element>
		</xsd:all>
	</xsd:complexType>

	<xsd:complexType name="LevelsType">
		<xsd:sequence>
			<xsd:element name="Level" type="LevelType" minOccurs="1" maxOccurs="unbounded"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="LevelType">
		<xsd:sequence minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="LevelMetadataElement" type="LevelMetadataElementType" minOccurs="0" maxOccurs="unbounded"></xsd:element>
		</xsd:sequence>
		<xsd:attribute name="nameID" type="xsd:ID" use="required"></xsd:attribute>
		<xsd:attribute name="iconFileName" type="xsd:string" use="required"></xsd:attribute>
		<xsd:attribute name="allowedSublevelNameRefs" type="xsd:IDREFS" use="optional"></xsd:attribute>
		<xsd:attributeGroup ref="levelSemantics"></xsd:attributeGroup>
	</xsd:complexType>
	
	<xsd:attributeGroup name="levelSemantics">
		<xsd:attribute name="isTrash" type="xsd:boolean" use="optional"></xsd:attribute>
		<!-- <xsd:attribute name="isFile" type="xsd:boolean" use="optional"></xsd:attribute> -->
	</xsd:attributeGroup>

	<xsd:complexType name="LevelMetadataElementType">
		<xsd:attribute name="accessorNameRef" type="xsd:IDREF" use="required"></xsd:attribute>
		<xsd:attribute name="isMandatory" type="xsd:boolean" use="required"></xsd:attribute>
		<xsd:attribute name="isRepeatable" type="xsd:boolean" use="required"></xsd:attribute>
		<xsd:attribute name="isAlwaysDisplayed" type="xsd:boolean" use="optional"></xsd:attribute>
		<xsd:attribute name="isReadOnly" type="xsd:boolean" use="optional"></xsd:attribute>
		<xsd:attribute name="keepInTemplate" type="xsd:boolean" use="optional"></xsd:attribute>
		<xsd:attribute name="displayRows" type="xsd:integer" use="optional"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="MetadataElementsType">
		<xsd:sequence>
			<xsd:element name="AllowedValuesSeparator" type="xsd:string" minOccurs="0" maxOccurs="1"></xsd:element>
			<xsd:sequence>
				<xsd:element name="MetadataElement" type="MetadataElementType" minOccurs="0" maxOccurs="unbounded"></xsd:element>
			</xsd:sequence>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="MetadataElementType">
		<xsd:attribute name="accessorNameID" type="xsd:ID" use="required"></xsd:attribute>
		<xsd:attribute name="validatorClassName" type="xsd:string" use="optional"></xsd:attribute>
		<xsd:attribute name="postActionClassName" type="xsd:string" use="optional"></xsd:attribute>
		<xsd:attribute name="allowedValues" type="xsd:string" use="optional"></xsd:attribute>
		<xsd:attribute name="allowedValuesType" use="optional">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="stringList" />
					<xsd:enumeration value="skosFile" />
					<xsd:enumeration value="csvFile" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="defaultExpression" type="xsd:string" use="optional"></xsd:attribute>
	</xsd:complexType>
</xsd:schema>

=== culturecommunication/octave/docuteam-packer/src/test/resources/config/levels.xml
<?xml version="1.0" encoding="UTF-8"?>
<LEVELS:Config
	xmlns:LEVELS="http://www.docuteam.ch/xmlns/levels"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.docuteam.ch/xmlns/levels		levels.xsd">

	<LEVELS:MetadataElements>
		<LEVELS:AllowedValuesSeparator>;</LEVELS:AllowedValuesSeparator>
		<LEVELS:MetadataElement					accessorNameID="accessPolicy"/>
		<LEVELS:MetadataElement					accessorNameID="accessRestriction"/>
		<LEVELS:MetadataElement					accessorNameID="accessRestrictionExplanation"/>
		<LEVELS:MetadataElement					accessorNameID="accessRestrictionPeriod"/>
		<LEVELS:MetadataElement					accessorNameID="accessRestrictionPeriodBaseYear"/>
		<LEVELS:MetadataElement					accessorNameID="accessRestrictionClassification"/>
		<LEVELS:MetadataElement					accessorNameID="accessRestrictionPrivacy"/>
		<LEVELS:MetadataElement					accessorNameID="accessRestrictionStatus"/>
		<LEVELS:MetadataElement					accessorNameID="accessRestrictionStatusExplanation"/>
		<LEVELS:MetadataElement					accessorNameID="accessRestrictionIsPublic"/>
		<LEVELS:MetadataElement					accessorNameID="accessRestrictionClosureYear"/>
		<LEVELS:MetadataElement					accessorNameID="accessRestrictionIsMetadataPublic"/>
		<LEVELS:MetadataElement					accessorNameID="usagePermission"/>
		<LEVELS:MetadataElement					accessorNameID="usagePermissionExpiringDate"/>
		<LEVELS:MetadataElement					accessorNameID="retentionPolicy"/>
		<LEVELS:MetadataElement					accessorNameID="retentionPeriod"/>
		<LEVELS:MetadataElement					accessorNameID="retentionPeriodBaseYear"/>
		<LEVELS:MetadataElement					accessorNameID="accessNr"/>
		<LEVELS:MetadataElement					accessorNameID="reproductions"/>
		<LEVELS:MetadataElement					accessorNameID="appraisalAndDestruction"/>
		<LEVELS:MetadataElement					accessorNameID="appraisalHoldRule"/>
		<LEVELS:MetadataElement					accessorNameID="appraisalHoldOwner"/>
		<LEVELS:MetadataElement					accessorNameID="appraisalHoldReason"/>
		<LEVELS:MetadataElement					accessorNameID="appraisalHoldStartDate"/>
		<LEVELS:MetadataElement					accessorNameID="appraisalHoldEndDate"/>
		<LEVELS:MetadataElement					accessorNameID="appraisalHoldReassessingDate"/>
		<LEVELS:MetadataElement					accessorNameID="appraisalIsOnHold"/>
		<LEVELS:MetadataElement					accessorNameID="appraisalDateDisposed"/>
		<LEVELS:MetadataElement					accessorNameID="appraisalRetentionPeriod"/>
		<LEVELS:MetadataElement					accessorNameID="arrangement"/>
		<LEVELS:MetadataElement					accessorNameID="bibliography"/>
		<LEVELS:MetadataElement					accessorNameID="institution"/>
		<LEVELS:MetadataElement					accessorNameID="objectType"/>
		<LEVELS:MetadataElement					accessorNameID="compartment"/>
		<LEVELS:MetadataElement					accessorNameID="fundingSource"/>
		<LEVELS:MetadataElement					accessorNameID="institute"/>
		<LEVELS:MetadataElement					accessorNameID="journal"/>
		<LEVELS:MetadataElement					accessorNameID="keyword"/>
		<LEVELS:MetadataElement					accessorNameID="location"/>
		<LEVELS:MetadataElement					accessorNameID="method"/>
		<LEVELS:MetadataElement					accessorNameID="publisher"/>
		<LEVELS:MetadataElement					accessorNameID="editor"/>
		<LEVELS:MetadataElement					accessorNameID="authorGeneric"/>
		<LEVELS:MetadataElement					accessorNameID="designer"/>
		<LEVELS:MetadataElement					accessorNameID="photographer"/>
		<LEVELS:MetadataElement					accessorNameID="illustrator"/>
		<LEVELS:MetadataElement					accessorNameID="status"/>
		<LEVELS:MetadataElement					accessorNameID="university"/>
		<LEVELS:MetadataElement					accessorNameID="author"/>
		<LEVELS:MetadataElement					accessorNameID="involved"/>
		<LEVELS:MetadataElement					accessorNameID="responsible"/>
		<LEVELS:MetadataElement					accessorNameID="staff"/>
		<LEVELS:MetadataElement					accessorNameID="archivalHistory"/>
		<LEVELS:MetadataElement					accessorNameID="sourceType"/>
		<LEVELS:MetadataElement					accessorNameID="modeOfAcquisition"/>
		<LEVELS:MetadataElement					accessorNameID="PID"/>
		<LEVELS:MetadataElement					accessorNameID="registrationURL"/>
		<LEVELS:MetadataElement					accessorNameID="abstract"/>
		<LEVELS:MetadataElement					accessorNameID="languageNotes"/>
		<LEVELS:MetadataElement					accessorNameID="language"/>
		<LEVELS:MetadataElement					accessorNameID="origination"/>
		<LEVELS:MetadataElement					accessorNameID="originationAgency"/>
		<LEVELS:MetadataElement					accessorNameID="originationDepartment"/>
		<LEVELS:MetadataElement					accessorNameID="extent"/>
		<LEVELS:MetadataElement					accessorNameID="extentNote"/>
		<LEVELS:MetadataElement					accessorNameID="extentUnit"/>
		<LEVELS:MetadataElement					accessorNameID="material"/>
		<LEVELS:MetadataElement					accessorNameID="creationPeriod"/>
		<LEVELS:MetadataElement					accessorNameID="creationPeriodNotes"/>
		<LEVELS:MetadataElement					accessorNameID="fromYear"/>
		<LEVELS:MetadataElement					accessorNameID="toYear"/>
		<LEVELS:MetadataElement					accessorNameID="from"/>
		<LEVELS:MetadataElement					accessorNameID="to"/>
		<LEVELS:MetadataElement					accessorNameID="relationPeriod"/>
		<LEVELS:MetadataElement					accessorNameID="year"/>
		<LEVELS:MetadataElement					accessorNameID="refCode"/>
		<LEVELS:MetadataElement					accessorNameID="refCodeAdmin"/>
		<LEVELS:MetadataElement					accessorNameID="refCodeOld"/>
		<LEVELS:MetadataElement					accessorNameID="refCodeSeparator"/>
		<LEVELS:MetadataElement					accessorNameID="refCodeIsVisible"/>
		
		<LEVELS:MetadataElement					accessorNameID="publication"/>
		<LEVELS:MetadataElement					accessorNameID="edition"/>
		<LEVELS:MetadataElement					accessorNameID="invalid"/>
		<LEVELS:MetadataElement					accessorNameID="letter"/>
		<LEVELS:MetadataElement					accessorNameID="extentPrint"/>
		
		<LEVELS:MetadataElement					accessorNameID="accessionNumber"/>
		<LEVELS:MetadataElement					accessorNameID="unitTitleAdditional"/>
		<LEVELS:MetadataElement					accessorNameID="comment"/>
		<LEVELS:MetadataElement					accessorNameID="doiJournal"/>
		<LEVELS:MetadataElement					accessorNameID="project"/>
		<LEVELS:MetadataElement					accessorNameID="projectAbbreviation"/>
		<LEVELS:MetadataElement					accessorNameID="projectName"/>
		<LEVELS:MetadataElement					accessorNameID="projectTitle"/>
		<LEVELS:MetadataElement					accessorNameID="usage"/>
		<LEVELS:MetadataElement					accessorNameID="event"/>
		<LEVELS:MetadataElement					accessorNameID="harvestingURL"/>
		<LEVELS:MetadataElement					accessorNameID="harvestingDate"/>
		<LEVELS:MetadataElement					accessorNameID="harvestingFrequency"/>
		<LEVELS:MetadataElement					accessorNameID="harvestingEntryPoint"/>
		<LEVELS:MetadataElement					accessorNameID="harvestingEmailRights"/>
		<LEVELS:MetadataElement					accessorNameID="locationOfOriginals"/>
		<LEVELS:MetadataElement					accessorNameID="findingAids"/>
		<LEVELS:MetadataElement					accessorNameID="characteristics"/>
		<LEVELS:MetadataElement					accessorNameID="descriptionLevel"/>
		<LEVELS:MetadataElement					accessorNameID="descriptionLevelNotes"/>
		<LEVELS:MetadataElement					accessorNameID="revisions"/>
		<LEVELS:MetadataElement					accessorNameID="processInfoArchivist"/>
		<LEVELS:MetadataElement					accessorNameID="processInfoDate"/>
		<LEVELS:MetadataElement					accessorNameID="digitization"/>
		<LEVELS:MetadataElement					accessorNameID="descriptionRules"/>
		<LEVELS:MetadataElement					accessorNameID="relatedMaterial"/>
		<LEVELS:MetadataElement					accessorNameID="relatedMaterialExtern"/>
		<LEVELS:MetadataElement					accessorNameID="scopeContent"/>
		<LEVELS:MetadataElement					accessorNameID="conditionsOfReproductions"/>
		<LEVELS:MetadataElement					accessorNameID="biographicalHistory"/>
		<LEVELS:MetadataElement					accessorNameID="firstname"/>
		<LEVELS:MetadataElement					accessorNameID="lastname"/>
		<LEVELS:MetadataElement					accessorNameID="dateOfBirth"/>
		<LEVELS:MetadataElement					accessorNameID="nationality"/>
		<LEVELS:MetadataElement					accessorNameID="sex"/>
		<LEVELS:MetadataElement					accessorNameID="deathOfAuthor"/>
		<LEVELS:MetadataElement					accessorNameID="accruals"/>
		<LEVELS:MetadataElement					accessorNameID="characteristicsNote"/>
		<LEVELS:MetadataElement					accessorNameID="subject"/>
		
		<LEVELS:MetadataElement					accessorNameID="cartographicMaterial"/>
		<LEVELS:MetadataElement					accessorNameID="scale"/>
		<LEVELS:MetadataElement					accessorNameID="codeLocation"/>
		<LEVELS:MetadataElement					accessorNameID="creator"/>
		<LEVELS:MetadataElement					accessorNameID="dimensions"/>
		<LEVELS:MetadataElement					accessorNameID="dimensionsCategory"/>
		<LEVELS:MetadataElement					accessorNameID="DOI"/>
		<LEVELS:MetadataElement					accessorNameID="editionStatement"/>
		<LEVELS:MetadataElement					accessorNameID="fullLocation"/>
		<LEVELS:MetadataElement					accessorNameID="geogName"/>
		<LEVELS:MetadataElement					accessorNameID="institutionCreator"/>
		<LEVELS:MetadataElement					accessorNameID="institutionInvolved"/>
		<LEVELS:MetadataElement					accessorNameID="familyName"/>
		<LEVELS:MetadataElement					accessorNameID="function"/>
		<LEVELS:MetadataElement					accessorNameID="occupation"/>
		<LEVELS:MetadataElement					accessorNameID="ISBN"/>
		<LEVELS:MetadataElement					accessorNameID="ISSN"/>
		<LEVELS:MetadataElement					accessorNameID="URN"/>
		<LEVELS:MetadataElement					accessorNameID="placeOfPublication"/>
		<LEVELS:MetadataElement					accessorNameID="subjectGeneral"/>
		<LEVELS:MetadataElement					accessorNameID="uniformTitle"/>
		<LEVELS:MetadataElement					accessorNameID="unitTitleVarying"/>
		<LEVELS:MetadataElement					accessorNameID="format"/>
		<LEVELS:MetadataElement					accessorNameID="size"/>
		<LEVELS:MetadataElement					accessorNameID="date"/>
		<LEVELS:MetadataElement					accessorNameID="unitTitleOriginal"/>
		<LEVELS:MetadataElement					accessorNameID="filePlanPosition"/>
		<LEVELS:MetadataElement					accessorNameID="typeOfAcquisition"/>
	</LEVELS:MetadataElements>
